import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JDateChooser;

import java.time.LocalDate;
import java.time.Year;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Locale;
import javax.swing.SpinnerNumberModel;

public class HitungHariFrame extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPerhitunganHariFrame
     */
    public HitungHariFrame() {
        initComponents();
        initLogic();
    }
// ================== Konstanta & Formatter ==================
private static final Locale LOCALE_ID = new Locale("id","ID");
private static final String[] BULAN_ID = {
    "Januari","Februari","Maret","April","Mei","Juni",
    "Juli","Agustus","September","Oktober","November","Desember"
};
private static final DateTimeFormatter DTF_LONG =
        DateTimeFormatter.ofPattern("EEEE, d MMMM yyyy", LOCALE_ID);
// ================== Inisialisasi awal ==================


// ================== Util & Sinkronisasi ==================
private LocalDate toLocalDate(java.util.Date d) {
    return d.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
}

private YearMonth getYearMonthFromInputs() {
    int bulan = cmbBulan.getSelectedIndex() + 1; // 1..12
    int tahun = ((Number) spnTahun.getValue()).intValue();
    return YearMonth.of(tahun, bulan);
}

private void syncToCalendar() {
    if (calBulan == null) return;
    java.util.Calendar c = calBulan.getCalendar();
    if (c == null) c = java.util.Calendar.getInstance();
    c.set(java.util.Calendar.YEAR, ((Number) spnTahun.getValue()).intValue());
    c.set(java.util.Calendar.MONTH, cmbBulan.getSelectedIndex()); // 0..11
    c.set(java.util.Calendar.DAY_OF_MONTH, 1);
    calBulan.setCalendar(c);
}

private void syncFromCalendar() {
    if (calBulan == null || calBulan.getCalendar() == null) return;
    java.util.Calendar c = calBulan.getCalendar();
    cmbBulan.setSelectedIndex(c.get(java.util.Calendar.MONTH));
    spnTahun.setValue(c.get(java.util.Calendar.YEAR));
}

// ================== Logika Perhitungan ==================
private void hitungHariBulan() {
    YearMonth ym = getYearMonthFromInputs();
    int jmlHari = ym.lengthOfMonth();
    LocalDate first = ym.atDay(1);
    LocalDate last  = ym.atEndOfMonth();
    boolean kabisat = Year.isLeap(ym.getYear());

    lblHasil.setText("Jumlah hari: " + jmlHari);
    lblInfo.setText("Rentang: " + first.format(DTF_LONG) + " — " + last.format(DTF_LONG));
    if (lblKabisat != null) lblKabisat.setText("Tahun kabisat: " + (kabisat ? "Ya" : "Tidak"));
}

private void hitungSelisihTanggal() {
    if (tglA == null || tglB == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Komponen tanggal tidak tersedia.");
        return;
    }
    java.util.Date a = tglA.getDate();
    java.util.Date b = tglB.getDate();
    if (a == null || b == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Mohon isi kedua tanggal.");
        return;
    }
    LocalDate la = toLocalDate(a);
    LocalDate lb = toLocalDate(b);
    long diff = ChronoUnit.DAYS.between(la, lb);
    lblSelisih.setText("Selisih: " + Math.abs(diff) + " hari");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        rootPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panelA = new javax.swing.JPanel();
        lblBulan = new javax.swing.JLabel();
        cmbBulan = new javax.swing.JComboBox<>();
        lblTahun = new javax.swing.JLabel();
        spnTahun = new javax.swing.JSpinner();
        btnHitung = new javax.swing.JButton();
        calBulan = new com.toedter.calendar.JCalendar();
        lblHasil = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        lblKabisat = new javax.swing.JLabel();
        panelB = new javax.swing.JPanel();
        lblTA = new javax.swing.JLabel();
        tglA = new com.toedter.calendar.JDateChooser();
        lblTB = new javax.swing.JLabel();
        tglB = new com.toedter.calendar.JDateChooser();
        btnSelisih = new javax.swing.JButton();
        lblSelisih = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Perhitungan Hari");

        rootPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Aplikasi Perhitungan Hari");

        panelA.setBorder(javax.swing.BorderFactory.createTitledBorder("Perhitungan Hari per Bulan"));

        lblBulan.setText("Bulan");

        cmbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBulanActionPerformed(evt);
            }
        });

        lblTahun.setText("Tahun");

        spnTahun.setModel(new javax.swing.SpinnerNumberModel(2025, 1, 9999, 1));
        spnTahun.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnTahunStateChanged(evt);
            }
        });

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        calBulan.setDate(new java.util.Date(1761456929000L));
        calBulan.setPreferredSize(new java.awt.Dimension(280, 200));
        calBulan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calBulanPropertyChange(evt);
            }
        });

        lblHasil.setText("Jumlah hari : -");

        lblInfo.setText("Rentang : -");

        lblKabisat.setText("Tahun kabisat : -");

        javax.swing.GroupLayout panelALayout = new javax.swing.GroupLayout(panelA);
        panelA.setLayout(panelALayout);
        panelALayout.setHorizontalGroup(
            panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelALayout.createSequentialGroup()
                        .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKabisat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(panelALayout.createSequentialGroup()
                        .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelALayout.createSequentialGroup()
                                .addComponent(lblTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spnTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelALayout.createSequentialGroup()
                                .addComponent(lblBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHitung)))
                        .addGap(18, 18, 18)
                        .addComponent(calBulan, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))))
        );

        panelALayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbBulan, spnTahun});

        panelALayout.setVerticalGroup(
            panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelALayout.createSequentialGroup()
                        .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBulan)
                            .addComponent(cmbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHitung))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTahun)
                            .addComponent(spnTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(calBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHasil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKabisat)
                .addGap(12, 12, 12))
        );

        panelB.setBorder(javax.swing.BorderFactory.createTitledBorder("Selisih Dua Tanggal"));

        lblTA.setText("Tanggal A");

        lblTB.setText("Tanggal B");

        btnSelisih.setText("Hitung Selisih");
        btnSelisih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelisihActionPerformed(evt);
            }
        });

        lblSelisih.setText("Selisih : -");

        javax.swing.GroupLayout panelBLayout = new javax.swing.GroupLayout(panelB);
        panelB.setLayout(panelBLayout);
        panelBLayout.setHorizontalGroup(
            panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBLayout.createSequentialGroup()
                        .addComponent(lblTA, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglA, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lblTB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglB, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelBLayout.createSequentialGroup()
                        .addComponent(btnSelisih)
                        .addGap(64, 64, 64)
                        .addComponent(lblSelisih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBLayout.setVerticalGroup(
            panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTA)
                    .addGroup(panelBLayout.createSequentialGroup()
                        .addGroup(panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tglB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTB, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(tglA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSelisih)
                            .addComponent(btnSelisih))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        hitungHariBulan();
    }//GEN-LAST:event_btnHitungActionPerformed

    private void spnTahunStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnTahunStateChanged
        syncToCalendar();
    }//GEN-LAST:event_spnTahunStateChanged

    private void cmbBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBulanActionPerformed
        syncToCalendar();
    }//GEN-LAST:event_cmbBulanActionPerformed

    private void calBulanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_calBulanPropertyChange
        String p = evt.getPropertyName();
        if ("calendar".equals(p) || "month".equals(p) || "year".equals(p)) {
            syncFromCalendar();
        }
    }//GEN-LAST:event_calBulanPropertyChange

    private void btnSelisihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelisihActionPerformed
        hitungSelisihTanggal();
    }//GEN-LAST:event_btnSelisihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HitungHariFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnSelisih;
    private com.toedter.calendar.JCalendar calBulan;
    private javax.swing.JComboBox<String> cmbBulan;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel lblBulan;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblKabisat;
    private javax.swing.JLabel lblSelisih;
    private javax.swing.JLabel lblTA;
    private javax.swing.JLabel lblTB;
    private javax.swing.JLabel lblTahun;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelA;
    private javax.swing.JPanel panelB;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JSpinner spnTahun;
    private com.toedter.calendar.JDateChooser tglA;
    private com.toedter.calendar.JDateChooser tglB;
    // End of variables declaration//GEN-END:variables

    private void initLogic() {
        cmbBulan.removeAllItems(); 
        // Masukkan semua bulan dari array
        for (String bulan : BULAN_ID) {
            cmbBulan.addItem(bulan);
        }

        // 2. Mengatur Spinner Tahun
        // Atur agar tahun memiliki rentang, misal 1900-2100
        // Ambil tahun saat ini
        int tahunIni = LocalDate.now().getYear();
        // Buat model spinner dengan nilai awal=tahunIni, min=1900, max=2100, step=1
        // Perlu import javax.swing.SpinnerNumberModel;
        SpinnerNumberModel modelTahun = new SpinnerNumberModel(tahunIni, 1900, 2100, 1);
        spnTahun.setModel(modelTahun);
        // Baris ini penting agar editor spinner tidak menggunakan format ribuan (misal "2.025")
        spnTahun.setEditor(new javax.swing.JSpinner.NumberEditor(spnTahun, "#"));


        // 3. Atur nilai awal berdasarkan tanggal hari ini
        LocalDate hariIni = LocalDate.now();
        cmbBulan.setSelectedIndex(hariIni.getMonthValue() - 1); // getMonthValue() -> 1..12, SelectedIndex -> 0..11
        // spnTahun sudah diatur ke tahunIni saat pembuatan model
        
        // 4. Atur JDateChooser dengan tanggal hari ini
        // Kita perlu konversi dari LocalDate ke java.util.Date
        java.util.Date tglUtilHariIni = java.sql.Date.valueOf(hariIni);
        tglA.setDate(tglUtilHariIni);
        tglB.setDate(tglUtilHariIni);

        // 5. Jalankan sinkronisasi dan perhitungan awal
        syncToCalendar();    // Sinkronkan JCalendar dengan ComboBox/Spinner
        hitungHariBulan(); // Jalankan perhitungan pertama kali agar label tidak kosong
        hitungSelisihTanggal(); // Inisialisasi label selisih
    }
}
